# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-13 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=b'static/images/no-img.jpg', upload_to=b'static/images'),
        ),
    ]
