# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-13 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeApp', '0004_auto_20180113_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to=b'recipes'),
        ),
    ]
