# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-13 07:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RecipeApp', '0004_auto_20180112_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecipeApp.Recipe')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('cantity', models.FloatField()),
                ('unit', models.CharField(max_length=10)),
                ('id_receip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecipeApp.Recipe')),
            ],
        ),
    ]
