# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-13 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeApp', '0005_auto_20180113_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.IntegerField(choices=[(1, 'Soup'), (2, 'Dessert'), (3, 'Main Course'), (4, 'Salad/ Starter')]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipes'),
        ),
    ]
